server:
  port: ${SERVICE_PORT:8001}
spring:
  profiles:
    default: dev
  application:
    name: test-api
  datasource:
      hikari:
          connection-timeout: 5000
          validation-timeout: 1000
          maximum-pool-size: 20
  jpa:
      properties:
          hibernate:
              format_sql: true
              use_sql_comments: true
      hibernate:
          naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://127.0.0.1:8000}/eureka/
  instance:
    hostname: localhost