###
POST http://localhost:8080/test
Content-Type: text/plain

val

###
GET http://localhost:8080/test/4
Content-Type: application/json

###
GET http://localhost:8080/test
Content-Type: application/json